package com.demo.entities;
// Generated Mar 3, 2024, 9:42:09 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account")
public class Account implements java.io.Serializable {

	private Integer accId;
	private String accUsername;
	private String accPassword;
	private String accFullname;
	private String accEmail;
	private String accPhone;
	private String accAddress;
	private boolean status;
	private Set<Role> roles = new HashSet<Role>(0);
	private Set<Blog> blogs = new HashSet<Blog>(0);
	private Set<Booking> bookings = new HashSet<Booking>(0);

	public Account() {
	}

	public Account(String accUsername, String accPassword, String accFullname, String accEmail, String accPhone,
			String accAddress, boolean status) {
		this.accUsername = accUsername;
		this.accPassword = accPassword;
		this.accFullname = accFullname;
		this.accEmail = accEmail;
		this.accPhone = accPhone;
		this.accAddress = accAddress;
		this.status = status;
	}

	public Account(String accUsername, String accPassword, String accFullname, String accEmail, String accPhone,
			String accAddress, boolean status, Set<Role> roles, Set<Blog> blogs, Set<Booking> bookings) {
		this.accUsername = accUsername;
		this.accPassword = accPassword;
		this.accFullname = accFullname;
		this.accEmail = accEmail;
		this.accPhone = accPhone;
		this.accAddress = accAddress;
		this.status = status;
		this.roles = roles;
		this.blogs = blogs;
		this.bookings = bookings;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "acc_id", unique = true, nullable = false)
	public Integer getAccId() {
		return this.accId;
	}

	public void setAccId(Integer accId) {
		this.accId = accId;
	}

	@Column(name = "acc_username", nullable = false, length = 250)
	public String getAccUsername() {
		return this.accUsername;
	}

	public void setAccUsername(String accUsername) {
		this.accUsername = accUsername;
	}

	@Column(name = "acc_password", nullable = false, length = 250)
	public String getAccPassword() {
		return this.accPassword;
	}

	public void setAccPassword(String accPassword) {
		this.accPassword = accPassword;
	}

	@Column(name = "acc_fullname", nullable = false, length = 250)
	public String getAccFullname() {
		return this.accFullname;
	}

	public void setAccFullname(String accFullname) {
		this.accFullname = accFullname;
	}

	@Column(name = "acc_email", nullable = false, length = 250)
	public String getAccEmail() {
		return this.accEmail;
	}

	public void setAccEmail(String accEmail) {
		this.accEmail = accEmail;
	}

	@Column(name = "acc_phone", nullable = false, length = 250)
	public String getAccPhone() {
		return this.accPhone;
	}

	public void setAccPhone(String accPhone) {
		this.accPhone = accPhone;
	}

	@Column(name = "acc_address", nullable = false, length = 250)
	public String getAccAddress() {
		return this.accAddress;
	}

	public void setAccAddress(String accAddress) {
		this.accAddress = accAddress;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "account_role", catalog = "booking_online", joinColumns = {
			@JoinColumn(name = "account_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "role_id", nullable = false, updatable = false) })
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Blog> getBlogs() {
		return this.blogs;
	}

	public void setBlogs(Set<Blog> blogs) {
		this.blogs = blogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Booking> getBookings() {
		return this.bookings;
	}

	public void setBookings(Set<Booking> bookings) {
		this.bookings = bookings;
	}

}
