package com.demo.entities;
// Generated Mar 4, 2024, 1:08:42 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.*;

/**
 * BlogsId generated by hbm2java
 */
@Embeddable
public class BlogsId implements java.io.Serializable {

	private int id;
	private String title;
	private String contents;
	private String photo;
	private int accountId;
	private Date created;
	private Date updated;
	private boolean status;

	public BlogsId() {
	}

	public BlogsId(int id, String title, String contents, String photo, int accountId, Date created, boolean status) {
		this.id = id;
		this.title = title;
		this.contents = contents;
		this.photo = photo;
		this.accountId = accountId;
		this.created = created;
		this.status = status;
	}

	public BlogsId(int id, String title, String contents, String photo, int accountId, Date created, Date updated,
			boolean status) {
		this.id = id;
		this.title = title;
		this.contents = contents;
		this.photo = photo;
		this.accountId = accountId;
		this.created = created;
		this.updated = updated;
		this.status = status;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "contents", nullable = false, length = 65535)
	public String getContents() {
		return this.contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

	@Column(name = "photo", nullable = false)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "account_id", nullable = false)
	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "updated", length = 10)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BlogsId))
			return false;
		BlogsId castOther = (BlogsId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getTitle() == castOther.getTitle()) || (this.getTitle() != null
						&& castOther.getTitle() != null && this.getTitle().equals(castOther.getTitle())))
				&& ((this.getContents() == castOther.getContents()) || (this.getContents() != null
						&& castOther.getContents() != null && this.getContents().equals(castOther.getContents())))
				&& ((this.getPhoto() == castOther.getPhoto()) || (this.getPhoto() != null
						&& castOther.getPhoto() != null && this.getPhoto().equals(castOther.getPhoto())))
				&& (this.getAccountId() == castOther.getAccountId())
				&& ((this.getCreated() == castOther.getCreated()) || (this.getCreated() != null
						&& castOther.getCreated() != null && this.getCreated().equals(castOther.getCreated())))
				&& ((this.getUpdated() == castOther.getUpdated()) || (this.getUpdated() != null
						&& castOther.getUpdated() != null && this.getUpdated().equals(castOther.getUpdated())))
				&& (this.isStatus() == castOther.isStatus());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getTitle() == null ? 0 : this.getTitle().hashCode());
		result = 37 * result + (getContents() == null ? 0 : this.getContents().hashCode());
		result = 37 * result + (getPhoto() == null ? 0 : this.getPhoto().hashCode());
		result = 37 * result + this.getAccountId();
		result = 37 * result + (getCreated() == null ? 0 : this.getCreated().hashCode());
		result = 37 * result + (getUpdated() == null ? 0 : this.getUpdated().hashCode());
		result = 37 * result + (this.isStatus() ? 1 : 0);
		return result;
	}

}
