package com.demo.entities;
// Generated Mar 3, 2024, 9:42:09 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import jakarta.persistence.*;

/**
 * Blog generated by hbm2java
 */
@Entity
@Table(name = "blog")
public class Blog implements java.io.Serializable {

	private Integer blogId;
	private Account account;
	private String blogTitle;
	private String blogContent;
	private String blogPhoto;
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date blogCreated;
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date blogUpdated;
	private boolean blogStatus;

	public Blog() {
	}

	public Blog(Account account, String blogTitle, String blogContent, String blogPhoto, Date blogCreated,
			Date blogUpdated, boolean blogStatus) {
		this.account = account;
		this.blogTitle = blogTitle;
		this.blogContent = blogContent;
		this.blogPhoto = blogPhoto;
		this.blogCreated = blogCreated;
		this.blogUpdated = blogUpdated;
		this.blogStatus = blogStatus;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "blog_id", unique = true, nullable = false)
	public Integer getBlogId() {
		return this.blogId;
	}

	public void setBlogId(Integer blogId) {
		this.blogId = blogId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "acc_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "blog_title", nullable = false, length = 250)
	public String getBlogTitle() {
		return this.blogTitle;
	}

	public void setBlogTitle(String blogTitle) {
		this.blogTitle = blogTitle;
	}

	@Column(name = "blog_content", nullable = false, length = 65535)
	public String getBlogContent() {
		return this.blogContent;
	}

	public void setBlogContent(String blogContent) {
		this.blogContent = blogContent;
	}

	@Column(name = "blog_photo", nullable = false, length = 250)
	public String getBlogPhoto() {
		return this.blogPhoto;
	}

	public void setBlogPhoto(String blogPhoto) {
		this.blogPhoto = blogPhoto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "blog_created", nullable = false, length = 26)
	public Date getBlogCreated() {
		return this.blogCreated;
	}

	public void setBlogCreated(Date blogCreated) {
		this.blogCreated = blogCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "blog_updated", nullable = false, length = 26)
	public Date getBlogUpdated() {
		return this.blogUpdated;
	}

	public void setBlogUpdated(Date blogUpdated) {
		this.blogUpdated = blogUpdated;
	}

	@Column(name = "blog_status", nullable = false)
	public boolean isBlogStatus() {
		return this.blogStatus;
	}

	public void setBlogStatus(boolean blogStatus) {
		this.blogStatus = blogStatus;
	}

}
