package com.demo.entities;
// Generated Mar 8, 2024, 11:16:40 AM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.*;

/**
 * BookingDetailsId generated by hbm2java
 */
@Embeddable
public class BookingDetailsId implements java.io.Serializable {

	private int bookingId;
	private int showsId;
	private int seatsId;

	public BookingDetailsId() {
	}

	public BookingDetailsId(int bookingId, int showsId, int seatsId) {
		this.bookingId = bookingId;
		this.showsId = showsId;
		this.seatsId = seatsId;
	}

	@Column(name = "booking_id", nullable = false)
	public int getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(int bookingId) {
		this.bookingId = bookingId;
	}

	@Column(name = "shows_id", nullable = false)
	public int getShowsId() {
		return this.showsId;
	}

	public void setShowsId(int showsId) {
		this.showsId = showsId;
	}

	@Column(name = "seats_id", nullable = false)
	public int getSeatsId() {
		return this.seatsId;
	}

	public void setSeatsId(int seatsId) {
		this.seatsId = seatsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BookingDetailsId))
			return false;
		BookingDetailsId castOther = (BookingDetailsId) other;

		return (this.getBookingId() == castOther.getBookingId()) && (this.getShowsId() == castOther.getShowsId())
				&& (this.getSeatsId() == castOther.getSeatsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBookingId();
		result = 37 * result + this.getShowsId();
		result = 37 * result + this.getSeatsId();
		return result;
	}

}
