package com.demo.entities;
// Generated Feb 26, 2024, 2:16:25 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.*;

/**
 * BookingDetails generated by hbm2java
 */
@Entity
@Table(name = "booking_details")
public class BookingDetails implements java.io.Serializable {

	private Integer id;
	private Booking booking;
	private ShowSeat showSeat;
	private int seatQuantity;
	private double total;

	public BookingDetails() {
	}

	public BookingDetails(Booking booking, ShowSeat showSeat, int seatQuantity, double total) {
		this.booking = booking;
		this.showSeat = showSeat;
		this.seatQuantity = seatQuantity;
		this.total = total;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "booking_id", nullable = false)
	public Booking getBooking() {
		return this.booking;
	}

	public void setBooking(Booking booking) {
		this.booking = booking;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "show_seat_id", nullable = false)
	public ShowSeat getShowSeat() {
		return this.showSeat;
	}

	public void setShowSeat(ShowSeat showSeat) {
		this.showSeat = showSeat;
	}

	@Column(name = "seat_quantity", nullable = false)
	public int getSeatQuantity() {
		return this.seatQuantity;
	}

	public void setSeatQuantity(int seatQuantity) {
		this.seatQuantity = seatQuantity;
	}

	@Column(name = "total", nullable = false, precision = 22, scale = 0)
	public double getTotal() {
		return this.total;
	}

	public void setTotal(double total) {
		this.total = total;
	}

}
