package com.demo.entities;
// Generated Mar 3, 2024, 9:42:09 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.springframework.format.annotation.DateTimeFormat;

import jakarta.persistence.*;

/**
 * Booking generated by hbm2java
 */
@Entity
@Table(name = "booking")
public class Booking implements java.io.Serializable {

	private Integer bkId;
	private Account account;
	private Voucher voucher;
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date bkCreated;
	private boolean bkStatus;
	private Set<BookingDetails> bookingDetailses = new HashSet<BookingDetails>(0);
	private Set<FoodBooking> foodBookings = new HashSet<FoodBooking>(0);

	public Booking() {
	}

	public Booking(Account account, Voucher voucher, Date bkCreated, boolean bkStatus) {
		this.account = account;
		this.voucher = voucher;
		this.bkCreated = bkCreated;
		this.bkStatus = bkStatus;
	}

	public Booking(Account account, Voucher voucher, Date bkCreated, boolean bkStatus,
			Set<BookingDetails> bookingDetailses, Set<FoodBooking> foodBookings) {
		this.account = account;
		this.voucher = voucher;
		this.bkCreated = bkCreated;
		this.bkStatus = bkStatus;
		this.bookingDetailses = bookingDetailses;
		this.foodBookings = foodBookings;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "bk_id", unique = true, nullable = false)
	public Integer getBkId() {
		return this.bkId;
	}

	public void setBkId(Integer bkId) {
		this.bkId = bkId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "acc_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vou_id", nullable = false)
	public Voucher getVoucher() {
		return this.voucher;
	}

	public void setVoucher(Voucher voucher) {
		this.voucher = voucher;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bk_created", nullable = false, length = 26)
	public Date getBkCreated() {
		return this.bkCreated;
	}

	public void setBkCreated(Date bkCreated) {
		this.bkCreated = bkCreated;
	}

	@Column(name = "bk_status", nullable = false)
	public boolean isBkStatus() {
		return this.bkStatus;
	}

	public void setBkStatus(boolean bkStatus) {
		this.bkStatus = bkStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "booking")
	public Set<BookingDetails> getBookingDetailses() {
		return this.bookingDetailses;
	}

	public void setBookingDetailses(Set<BookingDetails> bookingDetailses) {
		this.bookingDetailses = bookingDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "booking")
	public Set<FoodBooking> getFoodBookings() {
		return this.foodBookings;
	}

	public void setFoodBookings(Set<FoodBooking> foodBookings) {
		this.foodBookings = foodBookings;
	}

}
