package com.demo.entities;
// Generated Mar 8, 2024, 11:16:40 AM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.*;

import java.awt.print.Book;

/**
 * BookingDetails generated by hbm2java
 */
@Entity
@Table(name = "booking_details")
public class BookingDetails implements java.io.Serializable {

    private BookingDetailsId id;

    private Booking booking;
    private Seats seats;
    private Shows shows;
    private Double price;

    //	private Integer bookingId;
//	private String seat;
//	private Integer showId;
    public BookingDetails() {
    }

    public BookingDetails(BookingDetailsId id, Booking booking, Seats seats, Shows shows, Double price) {
        this.id = id;
        this.booking = booking;
        this.seats = seats;
        this.shows = shows;
        this.price = price;
    }

//	public BookingDetails(Integer bookingId, Seats seats, Integer showId, Double price) {
//		this.bookingId = bookingId;
//		this.seats = seats;
//		this.showId = showId;
//		this.price = price;
//	}

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "bookingId", column = @Column(name = "booking_id", nullable = false)),
            @AttributeOverride(name = "showsId", column = @Column(name = "shows_id", nullable = false)),
            @AttributeOverride(name = "seatsId", column = @Column(name = "seats_id", nullable = false))})

    public BookingDetailsId getId() {
        return this.id;
    }

    public void setId(BookingDetailsId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "booking_id", nullable = false, insertable = false, updatable = false)
    public Booking getBooking() {
        return this.booking;
    }

    public void setBooking(Booking booking) {
        this.booking = booking;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seats_id", nullable = false, insertable = false, updatable = false)
    public Seats getSeats() {
        return this.seats;
    }

    public void setSeats(Seats seats) {
        this.seats = seats;
    }

    @ManyToOne
    @JoinColumn(name = "shows_id", nullable = false, insertable = false, updatable = false)
    public Shows getShows() {
        return this.shows;
    }

    public void setShows(Shows shows) {
        this.shows = shows;
    }

    @Column(name = "price", nullable = false)
    public Double getPrice() {
        return this.price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

}
