package com.demo.entities;
// Generated Mar 4, 2024, 1:08:42 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.*;

/**
 * BookingDetailsId generated by hbm2java
 */
@Embeddable
public class BookingDetailsId implements java.io.Serializable {

	private int bookingId;
	private int movieShowId;
	private int seatsId;

	public BookingDetailsId() {
	}

	public BookingDetailsId(int bookingId, int movieShowId, int seatsId) {
		this.bookingId = bookingId;
		this.movieShowId = movieShowId;
		this.seatsId = seatsId;
	}

	@Column(name = "booking_id", nullable = false)
	public int getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(int bookingId) {
		this.bookingId = bookingId;
	}

	@Column(name = "movie_show_id", nullable = false)
	public int getMovieShowId() {
		return this.movieShowId;
	}

	public void setMovieShowId(int movieShowId) {
		this.movieShowId = movieShowId;
	}

	@Column(name = "seats_id", nullable = false)
	public int getSeatsId() {
		return this.seatsId;
	}

	public void setSeatsId(int seatsId) {
		this.seatsId = seatsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BookingDetailsId))
			return false;
		BookingDetailsId castOther = (BookingDetailsId) other;

		return (this.getBookingId() == castOther.getBookingId())
				&& (this.getMovieShowId() == castOther.getMovieShowId())
				&& (this.getSeatsId() == castOther.getSeatsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBookingId();
		result = 37 * result + this.getMovieShowId();
		result = 37 * result + this.getSeatsId();
		return result;
	}

}
