package com.demo.entities;
// Generated Feb 26, 2024, 2:16:25 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city", catalog = "booking_online")
public class City implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Cinema> cinemas = new HashSet<Cinema>(0);

	public City() {
	}

	public City(String name) {
		this.name = name;
	}

	public City(String name, Set<Cinema> cinemas) {
		this.name = name;
		this.cinemas = cinemas;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public Set<Cinema> getCinemas() {
		return this.cinemas;
	}

	public void setCinemas(Set<Cinema> cinemas) {
		this.cinemas = cinemas;
	}

}
