package com.demo.entities;
// Generated Mar 4, 2024, 1:08:42 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.*;

/**
 * FoodBookingDetailsId generated by hbm2java
 */
@Embeddable
public class FoodBookingDetailsId implements java.io.Serializable {

	private int bookingId;
	private int foodId;

	public FoodBookingDetailsId() {
	}

	public FoodBookingDetailsId(int bookingId, int foodId) {
		this.bookingId = bookingId;
		this.foodId = foodId;
	}

	@Column(name = "booking_id", nullable = false)
	public int getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(int bookingId) {
		this.bookingId = bookingId;
	}

	@Column(name = "food_id", nullable = false)
	public int getFoodId() {
		return this.foodId;
	}

	public void setFoodId(int foodId) {
		this.foodId = foodId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FoodBookingDetailsId))
			return false;
		FoodBookingDetailsId castOther = (FoodBookingDetailsId) other;

		return (this.getBookingId() == castOther.getBookingId()) && (this.getFoodId() == castOther.getFoodId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBookingId();
		result = 37 * result + this.getFoodId();
		return result;
	}

}
