package com.demo.entities;
// Generated Mar 8, 2024, 11:16:40 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * FoodMenu generated by hbm2java
 */
@Entity
@Table(name = "food_menu")
public class FoodMenu implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer price;
	private String photo;
	private Boolean status;
	private Set<FoodBookingDetails> foodBookingDetailses = new HashSet<FoodBookingDetails>(0);

	public FoodMenu() {
	}

	public FoodMenu(String name, Integer price, String photo, boolean status) {
		this.name = name;
		this.price = price;
		this.photo = photo;
		this.status = status;
	}

	public FoodMenu(String name, Integer price, String photo, boolean status,
			Set<FoodBookingDetails> foodBookingDetailses) {
		this.name = name;
		this.price = price;
		this.photo = photo;
		this.status = status;
		this.foodBookingDetailses = foodBookingDetailses;
	}

	@Id
	@GeneratedValue(strategy =GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", nullable = false)
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	@Column(name = "photo", nullable = false)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "status", nullable = false)
	public Boolean isStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "foodMenu")
	public Set<FoodBookingDetails> getFoodBookingDetailses() {
		return this.foodBookingDetailses;
	}

	public void setFoodBookingDetailses(Set<FoodBookingDetails> foodBookingDetailses) {
		this.foodBookingDetailses = foodBookingDetailses;
	}

}
