package com.demo.entities;
// Generated Mar 3, 2024, 9:42:09 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * Food generated by hbm2java
 */
@Entity
@Table(name = "food")
public class Food implements java.io.Serializable {

	private Integer foodId;
	private String foodName;
	private double foodPrice;
	private String foodPhoto;
	private Set<FoodBooking> foodBookings = new HashSet<FoodBooking>(0);

	public Food() {
	}

	public Food(String foodName, double foodPrice, String foodPhoto) {
		this.foodName = foodName;
		this.foodPrice = foodPrice;
		this.foodPhoto = foodPhoto;
	}

	public Food(String foodName, double foodPrice, String foodPhoto, Set<FoodBooking> foodBookings) {
		this.foodName = foodName;
		this.foodPrice = foodPrice;
		this.foodPhoto = foodPhoto;
		this.foodBookings = foodBookings;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "food_id", unique = true, nullable = false)
	public Integer getFoodId() {
		return this.foodId;
	}

	public void setFoodId(Integer foodId) {
		this.foodId = foodId;
	}

	@Column(name = "food_name", nullable = false, length = 250)
	public String getFoodName() {
		return this.foodName;
	}

	public void setFoodName(String foodName) {
		this.foodName = foodName;
	}

	@Column(name = "food_price", nullable = false, precision = 22, scale = 0)
	public double getFoodPrice() {
		return this.foodPrice;
	}

	public void setFoodPrice(double foodPrice) {
		this.foodPrice = foodPrice;
	}

	@Column(name = "food_photo", nullable = false, length = 250)
	public String getFoodPhoto() {
		return this.foodPhoto;
	}

	public void setFoodPhoto(String foodPhoto) {
		this.foodPhoto = foodPhoto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "food")
	public Set<FoodBooking> getFoodBookings() {
		return this.foodBookings;
	}

	public void setFoodBookings(Set<FoodBooking> foodBookings) {
		this.foodBookings = foodBookings;
	}

}
