package com.demo.entities;
// Generated Mar 3, 2024, 9:42:09 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.*;

/**
 * FoodBooking generated by hbm2java
 */
@Entity
@Table(name = "food_booking")
public class FoodBooking implements java.io.Serializable {

	private FoodBookingId id;
	private Booking booking;
	private Food food;
	private int quantity;
	private double price;

	public FoodBooking() {
	}

	public FoodBooking(FoodBookingId id, Booking booking, Food food, int quantity, double price) {
		this.id = id;
		this.booking = booking;
		this.food = food;
		this.quantity = quantity;
		this.price = price;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "bkId", column = @Column(name = "bk_id", nullable = false)),
			@AttributeOverride(name = "foodId", column = @Column(name = "food_id", nullable = false)) })
	public FoodBookingId getId() {
		return this.id;
	}

	public void setId(FoodBookingId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bk_id", nullable = false, insertable = false, updatable = false)
	public Booking getBooking() {
		return this.booking;
	}

	public void setBooking(Booking booking) {
		this.booking = booking;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "food_id", nullable = false, insertable = false, updatable = false)
	public Food getFood() {
		return this.food;
	}

	public void setFood(Food food) {
		this.food = food;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

}
