package com.demo.entities;
// Generated Feb 26, 2024, 2:16:25 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * Food generated by hbm2java
 */
@Entity
@Table(name = "food")
public class Food implements java.io.Serializable {

	private Integer id;
	private String name;
	private double price;
	private String photo;
	private Set<FoodBookingDetails> foodBookingDetailses = new HashSet<FoodBookingDetails>(0);

	public Food() {
	}

	public Food(String name, double price, String photo) {
		this.name = name;
		this.price = price;
		this.photo = photo;
	}

	public Food(String name, double price, String photo, Set<FoodBookingDetails> foodBookingDetailses) {
		this.name = name;
		this.price = price;
		this.photo = photo;
		this.foodBookingDetailses = foodBookingDetailses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "photo", nullable = false)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "food")
	public Set<FoodBookingDetails> getFoodBookingDetailses() {
		return this.foodBookingDetailses;
	}

	public void setFoodBookingDetailses(Set<FoodBookingDetails> foodBookingDetailses) {
		this.foodBookingDetailses = foodBookingDetailses;
	}

}
