package com.demo.entities;
// Generated Mar 3, 2024, 9:42:09 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.*;

/**
 * FoodBookingId generated by hbm2java
 */
@Embeddable
public class FoodBookingId implements java.io.Serializable {

	private int bkId;
	private int foodId;

	public FoodBookingId() {
	}

	public FoodBookingId(int bkId, int foodId) {
		this.bkId = bkId;
		this.foodId = foodId;
	}

	@Column(name = "bk_id", nullable = false)
	public int getBkId() {
		return this.bkId;
	}

	public void setBkId(int bkId) {
		this.bkId = bkId;
	}

	@Column(name = "food_id", nullable = false)
	public int getFoodId() {
		return this.foodId;
	}

	public void setFoodId(int foodId) {
		this.foodId = foodId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FoodBookingId))
			return false;
		FoodBookingId castOther = (FoodBookingId) other;

		return (this.getBkId() == castOther.getBkId()) && (this.getFoodId() == castOther.getFoodId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBkId();
		result = 37 * result + this.getFoodId();
		return result;
	}

}
