package com.demo.entities;
// Generated Mar 8, 2024, 11:16:40 AM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.*;

/**
 * FoodBookingDetailsId generated by hbm2java
 */
@Embeddable
public class FoodBookingDetailsId implements java.io.Serializable {

	private Integer bookingId;
	private Integer foodId;

	public FoodBookingDetailsId() {
	}

	public FoodBookingDetailsId(Integer bookingId, Integer foodId) {
		this.bookingId = bookingId;
		this.foodId = foodId;
	}

	@Column(name = "booking_id", nullable = false)
	public Integer getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(Integer bookingId) {
		this.bookingId = bookingId;
	}

	@Column(name = "food_id", nullable = false)
	public Integer getFoodId() {
		return this.foodId;
	}

	public void setFoodId(Integer foodId) {
		this.foodId = foodId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FoodBookingDetailsId))
			return false;
		FoodBookingDetailsId castOther = (FoodBookingDetailsId) other;

		return (this.getBookingId() == castOther.getBookingId()) && (this.getFoodId() == castOther.getFoodId());
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getBookingId();
		result = 37 * result + this.getFoodId();
		return result;
	}

}
