package com.demo.entities;
// Generated Mar 4, 2024, 1:08:42 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.*;

/**
 * FoodBookingDetails generated by hbm2java
 */
@Entity
@Table(name = "food_booking_details")
public class FoodBookingDetails implements java.io.Serializable {

	private FoodBookingDetailsId id;
	private Booking booking;
	private FoodMenu foodMenu;
	private int quantity;
	private int total;

	public FoodBookingDetails() {
	}

	public FoodBookingDetails(FoodBookingDetailsId id, Booking booking, FoodMenu foodMenu, int quantity, int total) {
		this.id = id;
		this.booking = booking;
		this.foodMenu = foodMenu;
		this.quantity = quantity;
		this.total = total;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "bookingId", column = @Column(name = "booking_id", nullable = false)),
			@AttributeOverride(name = "foodId", column = @Column(name = "food_id", nullable = false)) })
	public FoodBookingDetailsId getId() {
		return this.id;
	}

	public void setId(FoodBookingDetailsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "booking_id", nullable = false, insertable = false, updatable = false)
	public Booking getBooking() {
		return this.booking;
	}

	public void setBooking(Booking booking) {
		this.booking = booking;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "food_id", nullable = false, insertable = false, updatable = false)
	public FoodMenu getFoodMenu() {
		return this.foodMenu;
	}

	public void setFoodMenu(FoodMenu foodMenu) {
		this.foodMenu = foodMenu;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "total", nullable = false)
	public int getTotal() {
		return this.total;
	}

	public void setTotal(int total) {
		this.total = total;
	}

}
