package com.demo.entities;
// Generated Mar 8, 2024, 11:16:40 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * Hall generated by hbm2java
 */
@Entity
@Table(name = "hall")
public class Hall implements java.io.Serializable {

	private Integer id;
	private Cinema cinema;
	private String name;
	private Set<Seats> seatses = new HashSet<Seats>(0);

	public Hall() {
	}

	public Hall(Cinema cinema, String name) {
		this.cinema = cinema;
		this.name = name;
	}

	public Hall(Cinema cinema, String name, Set<Seats> seatses) {
		this.cinema = cinema;
		this.name = name;
		this.seatses = seatses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cinema_id", nullable = false)
	public Cinema getCinema() {
		return this.cinema;
	}

	public void setCinema(Cinema cinema) {
		this.cinema = cinema;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hall")
	public Set<Seats> getSeatses() {
		return this.seatses;
	}

	public void setSeatses(Set<Seats> seatses) {
		this.seatses = seatses;
	}

}
