package com.demo.entities;
// Generated Mar 8, 2024, 11:16:40 AM by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import jakarta.persistence.*;

/**
 * Hall generated by hbm2java
 */
@Entity
@Table(name = "hall")
public class Hall implements java.io.Serializable {

	private Integer id;
	private Cinema cinema;
	private String name;
	private List<Seats> seatses = new ArrayList<Seats>(0);
	private List<Shows> shows = new ArrayList<Shows>(0);

	public Hall() {
	}
	
	public Hall(Integer id) {
		this.id = id; 
	}

	public Hall(Cinema cinema, String name) {
		this.cinema = cinema;
		this.name = name;
	}

	public Hall(Cinema cinema, String name, List<Seats> seatses, List<Shows> shows) {
		this.cinema = cinema;
		this.name = name;
		this.seatses = seatses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cinema_id", nullable = false)
	public Cinema getCinema() {
		return this.cinema;
	}

	public void setCinema(Cinema cinema) {
		this.cinema = cinema;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hall")
	public List<Seats> getSeatses() {
		return this.seatses;
	}

	public void setSeatses(List<Seats> seatses) {
		this.seatses = seatses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hall")
	public List<Shows> getShows() {
		return shows;
	}

	public void setShows(List<Shows> shows) {
		this.shows = shows;
	}

	
	
}
