package com.demo.entities;
// Generated Mar 3, 2024, 9:42:09 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * Hall generated by hbm2java
 */
@Entity
@Table(name = "hall")
public class Hall implements java.io.Serializable {

	private Integer hallid;
	private Cinema cinema;
	private String hallName;
	private int hallSeats;
	private Set<Movieshow> movieshows = new HashSet<Movieshow>(0);
	private Set<Seat> seats = new HashSet<Seat>(0);

	public Hall() {
	}

	public Hall(Cinema cinema, String hallName, int hallSeats) {
		this.cinema = cinema;
		this.hallName = hallName;
		this.hallSeats = hallSeats;
	}

	public Hall(Cinema cinema, String hallName, int hallSeats, Set<Movieshow> movieshows, Set<Seat> seats) {
		this.cinema = cinema;
		this.hallName = hallName;
		this.hallSeats = hallSeats;
		this.movieshows = movieshows;
		this.seats = seats;
	}

	@Id
	@GeneratedValue(strategy =GenerationType.IDENTITY)

	@Column(name = "hallid", unique = true, nullable = false)
	public Integer getHallid() {
		return this.hallid;
	}

	public void setHallid(Integer hallid) {
		this.hallid = hallid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cine_id", nullable = false)
	public Cinema getCinema() {
		return this.cinema;
	}

	public void setCinema(Cinema cinema) {
		this.cinema = cinema;
	}

	@Column(name = "hall_name", nullable = false, length = 250)
	public String getHallName() {
		return this.hallName;
	}

	public void setHallName(String hallName) {
		this.hallName = hallName;
	}

	@Column(name = "hall_seats", nullable = false)
	public int getHallSeats() {
		return this.hallSeats;
	}

	public void setHallSeats(int hallSeats) {
		this.hallSeats = hallSeats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hall")
	public Set<Movieshow> getMovieshows() {
		return this.movieshows;
	}

	public void setMovieshows(Set<Movieshow> movieshows) {
		this.movieshows = movieshows;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hall")
	public Set<Seat> getSeats() {
		return this.seats;
	}

	public void setSeats(Set<Seat> seats) {
		this.seats = seats;
	}

}
