package com.demo.entities;
// Generated Mar 3, 2024, 9:42:09 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.springframework.format.annotation.DateTimeFormat;

import jakarta.persistence.*;

/**
 * Movie generated by hbm2java
 */
@Entity
@Table(name = "movie")
public class Movie implements java.io.Serializable {

	private Integer movId;
	private String movTitle;
	private String movDuration;
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date movReleaseDate;
	private String movGenre;
	private String movDirector;
	private String movCasters;
	private String movDescription;
	private String movLanguage;
	private String movPoster;
	private String movTrailer;
	private Set<Movieshow> movieshows = new HashSet<Movieshow>(0);
	private Set<Cinema> cinemas = new HashSet<Cinema>(0);

	public Movie() {
	}

	public Movie(String movTitle, String movDuration, Date movReleaseDate, String movGenre, String movDirector,
			String movCasters, String movDescription, String movLanguage, String movPoster, String movTrailer) {
		this.movTitle = movTitle;
		this.movDuration = movDuration;
		this.movReleaseDate = movReleaseDate;
		this.movGenre = movGenre;
		this.movDirector = movDirector;
		this.movCasters = movCasters;
		this.movDescription = movDescription;
		this.movLanguage = movLanguage;
		this.movPoster = movPoster;
		this.movTrailer = movTrailer;
	}

	public Movie(String movTitle, String movDuration, Date movReleaseDate, String movGenre, String movDirector,
			String movCasters, String movDescription, String movLanguage, String movPoster, String movTrailer,
			Set<Movieshow> movieshows, Set<Cinema> cinemas) {
		this.movTitle = movTitle;
		this.movDuration = movDuration;
		this.movReleaseDate = movReleaseDate;
		this.movGenre = movGenre;
		this.movDirector = movDirector;
		this.movCasters = movCasters;
		this.movDescription = movDescription;
		this.movLanguage = movLanguage;
		this.movPoster = movPoster;
		this.movTrailer = movTrailer;
		this.movieshows = movieshows;
		this.cinemas = cinemas;
	}

	@Id
	@GeneratedValue(strategy =GenerationType.IDENTITY)

	@Column(name = "mov_id", unique = true, nullable = false)
	public Integer getMovId() {
		return this.movId;
	}

	public void setMovId(Integer movId) {
		this.movId = movId;
	}

	@Column(name = "mov_title", nullable = false, length = 250)
	public String getMovTitle() {
		return this.movTitle;
	}

	public void setMovTitle(String movTitle) {
		this.movTitle = movTitle;
	}

	@Column(name = "mov_duration", nullable = false, length = 250)
	public String getMovDuration() {
		return this.movDuration;
	}

	public void setMovDuration(String movDuration) {
		this.movDuration = movDuration;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mov_release_date", nullable = false, length = 26)
	public Date getMovReleaseDate() {
		return this.movReleaseDate;
	}

	public void setMovReleaseDate(Date movReleaseDate) {
		this.movReleaseDate = movReleaseDate;
	}

	@Column(name = "mov_genre", nullable = false, length = 250)
	public String getMovGenre() {
		return this.movGenre;
	}

	public void setMovGenre(String movGenre) {
		this.movGenre = movGenre;
	}

	@Column(name = "mov_director", nullable = false, length = 250)
	public String getMovDirector() {
		return this.movDirector;
	}

	public void setMovDirector(String movDirector) {
		this.movDirector = movDirector;
	}

	@Column(name = "mov_casters", nullable = false, length = 250)
	public String getMovCasters() {
		return this.movCasters;
	}

	public void setMovCasters(String movCasters) {
		this.movCasters = movCasters;
	}

	@Column(name = "mov_description", nullable = false, length = 250)
	public String getMovDescription() {
		return this.movDescription;
	}

	public void setMovDescription(String movDescription) {
		this.movDescription = movDescription;
	}

	@Column(name = "mov_language", nullable = false, length = 250)
	public String getMovLanguage() {
		return this.movLanguage;
	}

	public void setMovLanguage(String movLanguage) {
		this.movLanguage = movLanguage;
	}

	@Column(name = "mov_poster", nullable = false, length = 250)
	public String getMovPoster() {
		return this.movPoster;
	}

	public void setMovPoster(String movPoster) {
		this.movPoster = movPoster;
	}

	@Column(name = "mov_trailer", nullable = false, length = 250)
	public String getMovTrailer() {
		return this.movTrailer;
	}

	public void setMovTrailer(String movTrailer) {
		this.movTrailer = movTrailer;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movie")
	public Set<Movieshow> getMovieshows() {
		return this.movieshows;
	}

	public void setMovieshows(Set<Movieshow> movieshows) {
		this.movieshows = movieshows;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "movies")
	public Set<Cinema> getCinemas() {
		return this.cinemas;
	}

	public void setCinemas(Set<Cinema> cinemas) {
		this.cinemas = cinemas;
	}

}
