package com.demo.entities;
// Generated Mar 8, 2024, 11:16:40 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.springframework.format.annotation.DateTimeFormat;

import jakarta.persistence.*;

/**
 * Movie generated by hbm2java
 */
@Entity
@Table(name = "movie")
public class Movie implements java.io.Serializable {

	private Integer id;
	private String title;
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date releaseDate;
	private Integer duration;
	private String genre;
	private String description;
	private String rating;
	private String directors;
	private String poster;
	private String trailer;
	private String casters;
	private Double price;
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date endDate;
	private Set<Shows> showses = new HashSet<Shows>(0);

	public Movie() {
	}
	
	public Movie(Integer id) {
		this.id = id;
	}

	public Movie(String title, Date releaseDate, Integer duration, String genre, String description, String rating,
			String directors, String poster, String trailer, String casters, Double price) {
		this.title = title;
		this.releaseDate = releaseDate;
		this.duration = duration;
		this.genre = genre;
		this.description = description;
		this.rating = rating;
		this.directors = directors;
		this.poster = poster;
		this.trailer = trailer;
		this.casters = casters;
		this.price = price;
	}

	public Movie(String title, Date releaseDate, Integer duration, String genre, String description, String rating,
			String directors, String poster, String trailer, String casters, Double price, Date endDate,
			Set<Shows> showses) {
		this.title = title;
		this.releaseDate = releaseDate;
		this.duration = duration;
		this.genre = genre;
		this.description = description;
		this.rating = rating;
		this.directors = directors;
		this.poster = poster;
		this.trailer = trailer;
		this.casters = casters;
		this.price = price;
		this.endDate = endDate;
		this.showses = showses;
	}

	@Id
	@GeneratedValue(strategy =GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "release_date", nullable = false, length = 10)
	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	@Column(name = "duration", nullable = false)
	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	@Column(name = "genre", nullable = false)
	public String getGenre() {
		return this.genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "rating", nullable = false)
	public String getRating() {
		return this.rating;
	}

	public void setRating(String rating) {
		this.rating = rating;
	}

	@Column(name = "directors", nullable = false)
	public String getDirectors() {
		return this.directors;
	}

	public void setDirectors(String directors) {
		this.directors = directors;
	}

	@Column(name = "poster", nullable = false)
	public String getPoster() {
		return this.poster;
	}

	public void setPoster(String poster) {
		this.poster = poster;
	}

	@Column(name = "trailer", nullable = false)
	public String getTrailer() {
		return this.trailer;
	}

	public void setTrailer(String trailer) {
		this.trailer = trailer;
	}

	@Column(name = "casters", nullable = false)
	public String getCasters() {
		return this.casters;
	}

	public void setCasters(String casters) {
		this.casters = casters;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movie")
	public Set<Shows> getShowses() {
		return this.showses;
	}

	public void setShowses(Set<Shows> showses) {
		this.showses = showses;
	}

	@Override
	public String toString() {
		return "Movie [id=" + id + ", title=" + title + ", releaseDate=" + releaseDate + ", duration=" + duration
				+ ", genre=" + genre + ", description=" + description + ", rating=" + rating + ", directors="
				+ directors + ", poster=" + poster + ", trailer=" + trailer + ", casters=" + casters + ", price="
				+ price + ", endDate=" + endDate + ", showses=" + showses + "]";
	}

	
	
	
}
