package com.demo.entities;
// Generated Mar 3, 2024, 9:42:09 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.springframework.format.annotation.DateTimeFormat;

import jakarta.persistence.*;

/**
 * Movieshow generated by hbm2java
 */
@Entity
@Table(name = "movieshow")
public class Movieshow implements java.io.Serializable {

	private Integer msid;
	private Hall hall;
	private Movie movie;
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date msStartDate;
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date msEndDate;
	private Set<BookingDetails> bookingDetailses = new HashSet<BookingDetails>(0);

	public Movieshow() {
	}

	public Movieshow(Hall hall, Movie movie, Date msStartDate, Date msEndDate) {
		this.hall = hall;
		this.movie = movie;
		this.msStartDate = msStartDate;
		this.msEndDate = msEndDate;
	}

	public Movieshow(Hall hall, Movie movie, Date msStartDate, Date msEndDate, Set<BookingDetails> bookingDetailses) {
		this.hall = hall;
		this.movie = movie;
		this.msStartDate = msStartDate;
		this.msEndDate = msEndDate;
		this.bookingDetailses = bookingDetailses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "msid", unique = true, nullable = false)
	public Integer getMsid() {
		return this.msid;
	}

	public void setMsid(Integer msid) {
		this.msid = msid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hall_id", nullable = false)
	public Hall getHall() {
		return this.hall;
	}

	public void setHall(Hall hall) {
		this.hall = hall;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mov_id", nullable = false)
	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ms_start_date", nullable = false, length = 26)
	public Date getMsStartDate() {
		return this.msStartDate;
	}

	public void setMsStartDate(Date msStartDate) {
		this.msStartDate = msStartDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ms_end_date", nullable = false, length = 26)
	public Date getMsEndDate() {
		return this.msEndDate;
	}

	public void setMsEndDate(Date msEndDate) {
		this.msEndDate = msEndDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movieshow")
	public Set<BookingDetails> getBookingDetailses() {
		return this.bookingDetailses;
	}

	public void setBookingDetailses(Set<BookingDetails> bookingDetailses) {
		this.bookingDetailses = bookingDetailses;
	}

}
