package com.demo.entities;
// Generated Feb 26, 2024, 2:16:25 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.springframework.format.annotation.DateTimeFormat;

import jakarta.persistence.*;

/**
 * Movie generated by hbm2java
 */
@Entity
@Table(name = "movie")
public class Movie implements java.io.Serializable {

	private Integer id;
	private String title;
	private int duration;
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date releaseDate;
	private String genre;
	private String rated;
	private String director;
	private String casters;
	private String description;
	private String language;
	private String poster;
	private String trailer;
	private Set<MovieShow> movieShows = new HashSet<MovieShow>(0);

	public Movie() {
	}

	public Movie(String title, int duration, Date releaseDate, String genre, String rated, String director,
			String casters, String description, String language, String poster, String trailer) {
		this.title = title;
		this.duration = duration;
		this.releaseDate = releaseDate;
		this.genre = genre;
		this.rated = rated;
		this.director = director;
		this.casters = casters;
		this.description = description;
		this.language = language;
		this.poster = poster;
		this.trailer = trailer;
	}

	public Movie(String title, int duration, Date releaseDate, String genre, String rated, String director,
			String casters, String description, String language, String poster, String trailer,
			Set<MovieShow> movieShows) {
		this.title = title;
		this.duration = duration;
		this.releaseDate = releaseDate;
		this.genre = genre;
		this.rated = rated;
		this.director = director;
		this.casters = casters;
		this.description = description;
		this.language = language;
		this.poster = poster;
		this.trailer = trailer;
		this.movieShows = movieShows;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "duration", nullable = false)
	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "release_date", nullable = false, length = 10)
	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	@Column(name = "genre", nullable = false)
	public String getGenre() {
		return this.genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

	@Column(name = "rated", nullable = false)
	public String getRated() {
		return this.rated;
	}

	public void setRated(String rated) {
		this.rated = rated;
	}

	@Column(name = "director", nullable = false)
	public String getDirector() {
		return this.director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	@Column(name = "casters", nullable = false)
	public String getCasters() {
		return this.casters;
	}

	public void setCasters(String casters) {
		this.casters = casters;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "language", nullable = false)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "poster", nullable = false)
	public String getPoster() {
		return this.poster;
	}

	public void setPoster(String poster) {
		this.poster = poster;
	}

	@Column(name = "trailer", nullable = false)
	public String getTrailer() {
		return this.trailer;
	}

	public void setTrailer(String trailer) {
		this.trailer = trailer;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movie")
	public Set<MovieShow> getMovieShows() {
		return this.movieShows;
	}

	public void setMovieShows(Set<MovieShow> movieShows) {
		this.movieShows = movieShows;
	}

}
