package com.demo.entities;
// Generated Feb 26, 2024, 2:16:25 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;
/**
 * Seat generated by hbm2java
 */
@Entity
@Table(name = "seat")
public class Seat implements java.io.Serializable {

	private Integer id;
	private Hall hall;
	private String seatRow;
	private int seatColumn;
	private Set<ShowSeat> showSeats = new HashSet<ShowSeat>(0);

	public Seat() {
	}

	public Seat(Hall hall, String seatRow, int seatColumn) {
		this.hall = hall;
		this.seatRow = seatRow;
		this.seatColumn = seatColumn;
	}

	public Seat(Hall hall, String seatRow, int seatColumn, Set<ShowSeat> showSeats) {
		this.hall = hall;
		this.seatRow = seatRow;
		this.seatColumn = seatColumn;
		this.showSeats = showSeats;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hall_id", nullable = false)
	public Hall getHall() {
		return this.hall;
	}

	public void setHall(Hall hall) {
		this.hall = hall;
	}

	@Column(name = "seat_row", nullable = false)
	public String getSeatRow() {
		return this.seatRow;
	}

	public void setSeatRow(String seatRow) {
		this.seatRow = seatRow;
	}

	@Column(name = "seat_column", nullable = false)
	public int getSeatColumn() {
		return this.seatColumn;
	}

	public void setSeatColumn(int seatColumn) {
		this.seatColumn = seatColumn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "seat")
	public Set<ShowSeat> getShowSeats() {
		return this.showSeats;
	}

	public void setShowSeats(Set<ShowSeat> showSeats) {
		this.showSeats = showSeats;
	}

}
