package com.demo.entities;
// Generated Mar 8, 2024, 11:16:40 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * Seats generated by hbm2java
 */
@Entity
@Table(name = "seats")
public class Seats implements java.io.Serializable {

	private Integer id;
	private Hall hall;
	private String row;
	private Integer number;
	private Set<BookingDetails> bookingDetailses = new HashSet<BookingDetails>(0);

	public Seats() {
	}

	public Seats(Hall hall, String row, Integer number) {
		this.hall = hall;
		this.row = row;
		this.number = number;
	}

	public Seats(Hall hall, String row, Integer number, Set<BookingDetails> bookingDetailses) {
		this.hall = hall;
		this.row = row;
		this.number = number;
		this.bookingDetailses = bookingDetailses;
	}

	@Id
	@GeneratedValue(strategy =GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hall_id", nullable = false)
	public Hall getHall() {
		return this.hall;
	}

	public void setHall(Hall hall) {
		this.hall = hall;
	}

	@Column(name = "row", nullable = false)
	public String getRow() {
		return this.row;
	}

	public void setRow(String row) {
		this.row = row;
	}

	@Column(name = "number", nullable = false)
	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "seats")
	public Set<BookingDetails> getBookingDetailses() {
		return this.bookingDetailses;
	}

	public void setBookingDetailses(Set<BookingDetails> bookingDetailses) {
		this.bookingDetailses = bookingDetailses;
	}

}
