package com.demo.entities;
// Generated Mar 4, 2024, 1:08:42 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * Shows generated by hbm2java
 */
@Entity
@Table(name = "shows")
public class Shows implements java.io.Serializable {

	private Integer id;
	private Cinema cinema;
	private Movie movie;
	private Date startDate;
	private Date endDate;
	private Set<MovieShow> movieShows = new HashSet<MovieShow>(0);

	public Shows() {
	}

	public Shows(Cinema cinema, Movie movie, Date startDate, Date endDate) {
		this.cinema = cinema;
		this.movie = movie;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public Shows(Cinema cinema, Movie movie, Date startDate, Date endDate, Set<MovieShow> movieShows) {
		this.cinema = cinema;
		this.movie = movie;
		this.startDate = startDate;
		this.endDate = endDate;
		this.movieShows = movieShows;
	}

	@Id
	@GeneratedValue(strategy =GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cinema_id", nullable = false)
	public Cinema getCinema() {
		return this.cinema;
	}

	public void setCinema(Cinema cinema) {
		this.cinema = cinema;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "movie_id", nullable = false)
	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", nullable = false, length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shows")
	public Set<MovieShow> getMovieShows() {
		return this.movieShows;
	}

	public void setMovieShows(Set<MovieShow> movieShows) {
		this.movieShows = movieShows;
	}

}
