package com.demo.entities;
// Generated Mar 3, 2024, 9:42:09 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * Voucher generated by hbm2java
 */
@Entity
@Table(name = "voucher")
public class Voucher implements java.io.Serializable {

	private Integer vouId;
	private String vouName;
	private double vouDiscount;
	private String vouExpiry;
	private Set<Booking> bookings = new HashSet<Booking>(0);

	public Voucher() {
	}

	public Voucher(String vouName, double vouDiscount, String vouExpiry) {
		this.vouName = vouName;
		this.vouDiscount = vouDiscount;
		this.vouExpiry = vouExpiry;
	}

	public Voucher(String vouName, double vouDiscount, String vouExpiry, Set<Booking> bookings) {
		this.vouName = vouName;
		this.vouDiscount = vouDiscount;
		this.vouExpiry = vouExpiry;
		this.bookings = bookings;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "vou_id", unique = true, nullable = false)
	public Integer getVouId() {
		return this.vouId;
	}

	public void setVouId(Integer vouId) {
		this.vouId = vouId;
	}

	@Column(name = "vou_name", nullable = false, length = 250)
	public String getVouName() {
		return this.vouName;
	}

	public void setVouName(String vouName) {
		this.vouName = vouName;
	}

	@Column(name = "vou_discount", nullable = false, precision = 22, scale = 0)
	public double getVouDiscount() {
		return this.vouDiscount;
	}

	public void setVouDiscount(double vouDiscount) {
		this.vouDiscount = vouDiscount;
	}

	@Column(name = "vou_expiry", nullable = false, length = 250)
	public String getVouExpiry() {
		return this.vouExpiry;
	}

	public void setVouExpiry(String vouExpiry) {
		this.vouExpiry = vouExpiry;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "voucher")
	public Set<Booking> getBookings() {
		return this.bookings;
	}

	public void setBookings(Set<Booking> bookings) {
		this.bookings = bookings;
	}

}
